ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS recipient_wallet TEXT NOT NULL DEFAULT '';
ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS gas_fee_sol NUMERIC(20,9) NOT NULL DEFAULT 0;
ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS ata_rent_sol NUMERIC(20,9) NOT NULL DEFAULT 0;
ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS total_fee_sol NUMERIC(20,9) NOT NULL DEFAULT 0;
ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS net_amount_usd NUMERIC(10,6) NOT NULL DEFAULT 0;
ALTER TABLE payout_requests ADD COLUMN IF NOT EXISTS ata_exists BOOLEAN NOT NULL DEFAULT false;
